name: "Apply org changes"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/production/*.tfvars'

jobs:
  apply-changes:
    name: "Org changes plan"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        env:
          TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "terraform"
          variables: |
            github_token = "${{ secrets.TERRAFORM_MANAGEMENT_GITHUB_TOKEN }}"
          var_file: |
            terraform/production/org.tfvars
            terraform/production/repositories.tfvars
            terraform/production/teams.tfvars

      - name: Commit changes
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "State changes after apply"
          force: false
